"""Build the PR title + body from data Phases 9-18 already persisted
(docs/AEGIS_IMPLEMENTATION_PLAN.md Section 27, ADR-0015).

The §27 subset of the 18-section report (the full builder is Phase 23):
summary, issue reference, files changed, tests added, tests executed +
results, review results, risk, confidence, plan alignment, verification
verdict, known limitations. Pure reads; no AI.
"""

from __future__ import annotations

from sqlalchemy.orm import Session

from app.repository.engineering_plans import EngineeringPlanRepository
from app.repository.implementations import ImplementationRepository
from app.repository.issues import IssueRepository
from app.repository.patches import PatchRepository
from app.repository.reviews import ReviewRepository
from app.repository.scoring import RiskAssessmentRepository
from app.repository.tasks import TaskRepository
from app.repository.test_cases import TestCaseRepository
from app.repository.test_executions import TestExecutionRepository
from app.repository.verifications import VerificationRepository

_FAILING = {"FAIL", "ERROR"}


def build_pr_title(db: Session, task_id: str) -> str:
    task = TaskRepository(db).get(task_id)
    title = (task.title if task else task_id).strip().splitlines()[0]
    return f"AEGIS: {title}"[:250]


def build_pr_body(db: Session, task_id: str) -> str:
    task = TaskRepository(db).get(task_id)
    plan = EngineeringPlanRepository(db).get_latest_by_task(task_id)
    impl = ImplementationRepository(db).get_latest_by_task(task_id)
    patch = (
        PatchRepository(db).get_by_implementation(impl.id) if impl is not None else None
    )
    cases = TestCaseRepository(db).list_latest_by_task(task_id)
    execution = TestExecutionRepository(db).get_latest_by_task(task_id)
    review = ReviewRepository(db).get_by_task(task_id)
    risk = RiskAssessmentRepository(db).get_by_task(task_id)
    verification = VerificationRepository(db).get_by_task(task_id)

    issue = None
    if task is not None and task.issue_id:
        issue = IssueRepository(db).get(task.issue_id)

    lines: list[str] = []
    a = lines.append

    a(f"## Summary\n\n{_summary(task, plan)}\n")

    a("## Issue reference\n")
    if issue is not None and issue.external_ref:
        a(f"- Issue: `{issue.external_ref}`")
    a(f"- AEGIS task: `{task_id}`\n")

    a("## Files changed\n")
    touched = list(patch.touched_paths) if patch is not None else []
    if touched:
        for p in touched:
            a(f"- `{p}`")
    else:
        a("- _(none recorded)_")
    a("")

    a("## Tests added\n")
    if cases:
        for c in cases:
            a(f"- `{c.path}::{c.name}` ({c.kind})")
    else:
        a("- _(none)_")
    a("")

    a("## Tests executed & results\n")
    a(_execution_summary(execution))
    a("")

    a("## Review results\n")
    a(_review_summary(review))
    a("")

    a("## Risk & confidence\n")
    if risk is not None:
        a(f"- Change Risk Score: **{risk.crs_value}** ({risk.crs_classification})")
        a(f"- Patch Confidence Score: **{risk.pcs_value}** ({risk.pcs_classification})")
    else:
        a("- _(not scored)_")
    a("")

    a("## Plan alignment\n")
    a(_alignment_summary(verification))
    a("")

    a("## Verification\n")
    a(_verification_summary(verification))
    a("")

    a("## Known limitations\n")
    a(_limitations(verification, review))
    a("")

    a("---\n_Generated by AEGIS. A PR is opened only after the task is VERIFIED._")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #


def _summary(task, plan) -> str:
    if plan is not None and plan.problem_interpretation:
        return plan.problem_interpretation.strip()
    if task is not None:
        return task.description_sanitized.strip()[:500]
    return "_(no summary available)_"


def _execution_summary(execution) -> str:
    if execution is None:
        return "- _(tests were not executed)_"
    results = execution.results or []
    passed = sum(1 for r in results if r.get("outcome") == "PASS")
    failed = sorted(r.get("test_id", "?") for r in results if r.get("outcome") in _FAILING)
    out = [f"- Outcome: **{execution.outcome}** ({passed}/{len(results)} passed)"]
    if failed:
        out.append(f"- Failing: {', '.join(f'`{t}`' for t in failed)}")
    return "\n".join(out)


def _review_summary(review) -> str:
    if review is None:
        return "- _(not reviewed)_"
    sev = (review.counts or {}).get("severity", {})
    parts = ", ".join(f"{k}: {v}" for k, v in sorted(sev.items())) or "no findings"
    blocking = "yes" if review.blocking else "no"
    return f"- Findings by severity: {parts}\n- Blocking: **{blocking}**"


def _alignment_summary(verification) -> str:
    if verification is None:
        return "- _(not verified)_"
    pa = verification.plan_alignment or {}
    return (
        f"- Steps implemented: {pa.get('steps_implemented', '?')}"
        f"/{pa.get('steps_total', '?')}\n"
        f"- Unplanned files: {pa.get('unplanned_files') or 'none'}"
    )


def _verification_summary(verification) -> str:
    if verification is None:
        return "- _(not verified)_"
    trace = verification.trace or {}
    return (
        f"- Verdict: **{verification.verdict}**\n"
        f"- Why safe: {trace.get('why_safe', '_(n/a)_')}"
    )


def _limitations(verification, review) -> str:
    items: list[str] = []
    if verification is not None:
        unknown = [
            c.get("name")
            for c in (verification.criteria or [])
            if c.get("verdict") == "UNKNOWN"
        ]
        if unknown:
            items.append(f"Unverified criteria: {', '.join(unknown)}")
    if review is not None and review.policy_gaps:
        items.append(f"Review policy gaps: {', '.join(review.policy_gaps)}")
    if not items:
        return "- _(none recorded)_"
    return "\n".join(f"- {i}" for i in items)


def touched_files_for_task(db: Session, task_id: str) -> list[str]:
    impl = ImplementationRepository(db).get_latest_by_task(task_id)
    if impl is None:
        return []
    patch = PatchRepository(db).get_by_implementation(impl.id)
    return list(patch.touched_paths) if patch is not None else []
