#!/usr/bin/env python3
"""Generate docs/API_REFERENCE.md from the FastAPI app's OpenAPI schema.

Single source of truth = the running app. Run with no arguments to print the
Markdown to stdout; run with ``--write`` to overwrite ``docs/API_REFERENCE.md``.
``backend/tests/docs/test_api_reference_fresh.py`` fails CI if the committed
file drifts from what this script produces.

    python scripts/gen_api_reference.py            # print
    python scripts/gen_api_reference.py --write    # update the doc
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_BACKEND = _REPO_ROOT / "backend"
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

DOC_PATH = _REPO_ROOT / "docs" / "API_REFERENCE.md"

_METHOD_ORDER = ["get", "post", "put", "patch", "delete", "options", "head"]


def _schema_name(node: dict) -> str:
    """Best-effort human name for a schema node (a $ref, an array of $ref, or inline)."""
    if not isinstance(node, dict):
        return "-"
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if node.get("type") == "array" and isinstance(node.get("items"), dict):
        return f"{_schema_name(node['items'])}[]"
    if "anyOf" in node or "oneOf" in node:
        parts = node.get("anyOf") or node.get("oneOf")
        return " | ".join(_schema_name(p) for p in parts)
    return node.get("type", "object")


def _body_schema(operation: dict) -> str:
    content = (operation.get("requestBody") or {}).get("content") or {}
    js = content.get("application/json") or {}
    return _schema_name(js.get("schema", {})) if js else "-"


def _response_summary(operation: dict) -> str:
    out = []
    for code, resp in sorted((operation.get("responses") or {}).items()):
        content = (resp or {}).get("content") or {}
        js = content.get("application/json") or {}
        name = _schema_name(js.get("schema", {})) if js else ""
        out.append(f"{code} {name}".strip())
    return "; ".join(out) or "-"


def _params(operation: dict) -> str:
    rows = []
    for p in operation.get("parameters") or []:
        loc = p.get("in", "?")
        req = "" if p.get("required") else "?"
        rows.append(f"{p.get('name')}{req} ({loc})")
    return ", ".join(rows) or "-"


def render(app) -> str:  # noqa: ANN001 -- FastAPI app
    spec = app.openapi()
    info = spec.get("info", {})
    paths = spec.get("paths", {})

    lines: list[str] = []
    lines.append("<!-- GENERATED by scripts/gen_api_reference.py -- do not edit by hand. -->")
    lines.append("<!-- Re-run `python scripts/gen_api_reference.py --write` after changing a route. -->")
    lines.append("")
    lines.append(f"# {info.get('title', 'API')} — API Reference")
    lines.append("")
    lines.append(
        f"OpenAPI {spec.get('openapi', '?')} · app version `{info.get('version', '?')}`. "
        "This file is generated from the live FastAPI schema; the interactive docs are "
        "at `/docs` and the raw schema at `/openapi.json` when the app is running."
    )
    lines.append("")
    lines.append(
        "Auth: mutating routes declare an RBAC role (viewer / operator / approver / "
        "admin). Enforcement is a no-op unless `AEGIS_AUTH_ENABLED=true` (see "
        "`docs/OPERATOR_GUIDE.md`)."
    )
    lines.append("")

    # ---- operation index -------------------------------------------------- #
    ops: list[tuple[str, str, dict]] = []
    for path in sorted(paths):
        methods = paths[path]
        for method in sorted(methods, key=lambda m: _METHOD_ORDER.index(m) if m in _METHOD_ORDER else 99):
            if method not in _METHOD_ORDER:
                continue
            ops.append((path, method.upper(), methods[method]))

    lines.append("## Endpoints")
    lines.append("")
    lines.append(f"{len(ops)} operations.")
    lines.append("")
    lines.append("| Method | Path | Summary | Tags |")
    lines.append("|---|---|---|---|")
    for path, method, op in ops:
        summary = (op.get("summary") or (op.get("description") or "").split("\n")[0] or "").strip()
        summary = summary.replace("|", "\\|")
        tags = ", ".join(op.get("tags") or [])
        lines.append(f"| {method} | `{path}` | {summary} | {tags} |")
    lines.append("")

    # ---- per-endpoint detail ------------------------------------------- #
    lines.append("## Details")
    lines.append("")
    for path, method, op in ops:
        lines.append(f"### {method} `{path}`")
        lines.append("")
        summary = (op.get("summary") or "").strip()
        if summary:
            lines.append(summary)
            lines.append("")
        lines.append(f"- **Params:** {_params(op)}")
        lines.append(f"- **Request body:** `{_body_schema(op)}`")
        lines.append(f"- **Responses:** {_response_summary(op)}")
        tags = ", ".join(op.get("tags") or [])
        if tags:
            lines.append(f"- **Tags:** {tags}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    from app.main import app

    text = render(app)
    if "--write" in sys.argv:
        DOC_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {DOC_PATH.relative_to(_REPO_ROOT)} ({len(text.splitlines())} lines)")
    else:
        try:
            sys.stdout.reconfigure(encoding="utf-8")  # em dash / middot on any platform
        except (AttributeError, ValueError):
            pass
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
